### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by mmmoli** [este/este-redux-firebase#3]
I could do it, but it should probably have it under [steida](https://www.npmjs.com/~steida), no?

**Comment by steida** [comment]
Sure.

**Comment by steida** [comment]
come to https://gitter.im/este/este please

**Comment by steida** [comment]
I will add you as collaborator

**Comment by steida** [comment]
Or I have a better idea. Please publish it on your account, and add me as collaborator later. Then send PR to Este, and your awesome work is done today :+1:

**Comment by mmmoli** [comment]
on [NPM](https://www.npmjs.com/package/este-firebase-redux)

**Comment by steida** [comment]
Awesome, thank you! I have no time to replace it with lib, maybe... next next week :-/

**Comment by mmmoli** [comment]
np.

Added you as an owner.

**Comment by steida** [comment]
On the happier note, you will see a lot of advanced Firebase patterns like aggregations etc. soon here https://github.com/steida/vetoapp
